drop table "AspNetRoleClaims" CASCADE;
drop table public."AspNetRoles" CASCADE;
drop table public."AspNetUserClaims" CASCADE;
drop table public."AspNetUserLogins" CASCADE;
drop table public."AspNetUserRoles" CASCADE;
drop table public."AspNetUserTokens" CASCADE;
drop table public."AspNetUsers" CASCADE;
drop table public."Bids" CASCADE;
drop table public."Comments" CASCADE ;
drop table public."Listings" CASCADE;
drop table public."__EFMigrationsHistory" CASCADE;